i18n_tr:
  i18n_dir: lib/i18n
#  source_file: lib/i18n/_source_text.dart
#  config_file: lib/i18n/i18n_config.dart
  source_locale: zh_CN
  fallback_locale: zh_CN
  system_label: 跟随系统
  langs:
    - locale: zh_CN
      label: 简体中文
      file: zh_cn.dart
      map: zhCN
    - locale: en_US
      label: English
      file: en_us.dart
      map: enUS
    - locale: ja_JP
      label: 日本語
      file: ja_jp.dart
      map: jaJP
  prune_unused: true
  migrations:
    - from: 新增的
      to: 新增