name: i18n_tr_example
description: Example app for i18n_tr
publish_to: none
version: 0.0.1

environment:
  sdk: ^3.9.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  i18n_tr:
    path: ..

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

i18n_tr:
  i18n_dir: lib/i18n
#  source_file: lib/i18n/_source_text.dart
#  config_file: lib/i18n/i18n_config.dart
  source_locale: zh_CN
  fallback_locale: zh_CN
  system_label: 跟随系统
  langs:
    - locale: zh_CN
      label: 简体中文
      file: zh_cn.dart
      map: zhCN
    - locale: en_US
      label: English
      file: en_us.dart
      map: enUS
    - locale: ja_JP
      label: 日本語
      file: ja_jp.dart
      map: jaJP